### ISSUE TITLE
conexion a red desde maquina virtual vbox con xanadu

### ISSUE THREAD

**Issue by riztan** [xanadu-linux/xanadu-linux#1]
Buenas, acabo de instalar xanadu en una maquina virtual y no he podido conectarla con la red local. La maquina toma dirección ip bien, pero no ha logrado comunicación, un simple ping no funciona.

Cuando lo inicio como prueba desde la imagen del cd, conecta sin problema. Pero ya instalado no.

Gracias de antemano.

Saludos

**Comment by sinfallas** [comment]
Saludos...
Necesitamos que seas un poco mas especifico al describir tu error para poder ayudarte, en esta dirección https://github.com/xanadu-linux/xanadu-linux hay unos pasos a seguir para reportar un error, gracias de antemano.
